### ISSUE TITLE
😲 a priori, x et y devraient être positives ou nulles 

### ISSUE THREAD

**Issue by boisgera** [YoanRICHARD/Snake#1]
Dans le fichier `SerpentMouvant.py`, faire en sorte que l'on n'affecte jamais aux variables `x` et `y` des valeurs négatives (comme évoqué en cours), sans changer globalement la fonctionnalité du code.

(Cf. <https://fr.wikipedia.org/wiki/Principe_de_moindre_surprise>)

**Comment by YoanRICHARD** [comment]
En effet cela n'est pas très poli de ma part. Si la correction n'apparait pas dans mes commits plus récent c'est que j'ai pris un nouveau départ dans mon projet. Cependant, merci beaucoup pour le commentaire.

**Comment by boisgera** [comment]
OK, vu, merci !
